### ISSUE TITLE
My incidents

### ISSUE THREAD

**Issue by Dong-Ying** [aidsgo/AidsGoAPI#3]
My incidents and incidents list返回的结果结构是不一样的

**Comment by yanyujason** [comment]
Format for My Incidents.
{
  "2452b95d-d382-4dbd-9603-6ba6e26df47e": {
    "id": "2452b95d-d382-4dbd-9603-6ba6e26df47e",
    "name": "xiao ming",
    "location": {
      "lat": 34.256403,
      "lng": 108.953661
    },
    "time": "2016-11-07T11:34:40.886Z",
    "taken": [
      "11e25970-9a21-4716-bee7-d3ec02d063c7"
    ],
    "resolved": null
  }
}

remove Key - distance
